name:                hsDummyImage
version:             0.9.0
github:              "DummyFiles/hsDummyImage"
license:             Apache-2.0
author:              "S0D3S"
copyright:           "2022 S0D3S"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DummyFiles/hsDummyImage#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- optparse-applicative
- repa
- zlib
- bytestring
- filepath
- binary
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- src/Icon.o

library:
  source-dirs: src

executables:
  binary-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -T"'
    - -fllvm
    - -O2
    - -optlo-O3
    dependencies:
    - hsDummyImage

tests:
  hsDummyImage-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsDummyImage
