
name: Compile binaries for the current release
on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  Linux-MacOS-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest]
    
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Add LLVM to path [${{ matrix.os }}]
        if: runner.os == 'macOS'
        run: |
          echo $(brew --prefix llvm)*/bin >> $GITHUB_PATH
          
      - name: Install LLVM and Clang
        if: runner.os == 'Linux'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13"
          
      - name: Install LLVM dep
        if: runner.os == 'Linux'
        run: sudo apt install libtinfo5
      
      - name: Delete Icon.o from package.yaml
        run: |          
          sed '/- src\/Icon\.o/d' ./package.yaml > temp && mv temp ./package.yaml
          
      - name: Build i386
        if: false && runner.os == 'macOS'
        run: |
          stack build --local-bin-path=bin --copy-bins --arch i386
          mv bin/binary-exe "bin/$(echo '${{github.repository}}' | rev | cut -d '/' -f 1 | rev)-${{runner.os}}-x86"
         
      - name: Build x86_64
        run: |
          stack build --local-bin-path=bin --copy-bins --arch x86_64
          mv bin/binary-exe "bin/$(echo '${{github.repository}}' | rev | cut -d '/' -f 1 | rev)-${{runner.os}}-x86_64"
          
      - name: Add binary name to ENV
        working-directory: ./bin
        run: |
          echo "BINARY_NAME=$(ls * | head -n1)"  >> $GITHUB_ENV
          
      - name: Build summary
        run: ls bin
          
      - name: Add ${{runner.os}} binary to release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
          
      - name: Job summary
        run: |
          echo "### ✔ Build ${{runner.os}}" >> $GITHUB_STEP_SUMMARY
          
      - name: Run performance test
        id: perf-test
        uses: ./.github/actions/test_performance
        with:
          binary-name: ${{env.BINARY_NAME}}
          binary-run-command: ./${{env.BINARY_NAME}}
      
      - name: Perf test summary
        run: |
          cat ${{steps.perf-test.outputs.md-output}} >> $GITHUB_STEP_SUMMARY
          echo "MD_REPORT<<EOF" >> $GITHUB_ENV
          echo "<details><summary>📈 Performance test. <b>[${{runner.os}}]</b> build</summary>" >> $GITHUB_ENV
          echo -e "\n<br>\n" >> $GITHUB_ENV
          cat ${{steps.perf-test.outputs.md-output}} >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "</details>" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Add report to release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{env.MD_REPORT}}
          append_body: true
          
        

  Windows-build:
    strategy:
      matrix:
        os: [windows-latest] 
        
    runs-on: ${{matrix.os}}

    env:
      BACKEND_ROOT: 'llvm_backend'
      LLVM_ZIP_NAME: 'llvm_zip.7z'
      LLVM_ROOT_NAME: 'llvm'
      CLANG_ZIP_NAME: 'clang_zip.7z'
      CLANG_ROOT_NAME: 'clang'
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Downloading LLVM Windows binary
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with: 
          repo: 'vovkos/llvm-package-windows'
          version: 'tags/llvm-12.0.1'
          file: 'llvm-12.0.1-windows-amd64-msvc15-msvcrt.7z'          
          target: '${{env.BACKEND_ROOT}}/${{env.LLVM_ZIP_NAME}}'

      - name: Extract LLVM
        run: |
          7z x -y ${{env.BACKEND_ROOT}}/llvm* -o${{env.BACKEND_ROOT}}/
          Get-ChildItem ${{env.BACKEND_ROOT}}/llvm-* | Rename-Item -NewName "${{env.LLVM_ROOT_NAME}}"
          echo "${{env.LLVM_ROOT}}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        env:
          LLVM_ROOT: "$pwd/${{env.BACKEND_ROOT}}/${{env.LLVM_ROOT_NAME}}/bin"
          

      - name: Exctraction summary
        run: |
          ls $pwd/${{env.BACKEND_ROOT}}/${{env.LLVM_ROOT_NAME}}/bin/llc*
          
          echo ("LLVM llc exist: " + ((Get-Command "llc" -ErrorAction SilentlyContinue) -ne $null))
          echo ("LLVM clang(preinstalled) exist: " + ((Get-Command "clang" -ErrorAction SilentlyContinue) -ne $null))
          (&{If((Get-Command "llc" -ErrorAction SilentlyContinue) -eq $null -or (Get-Command "clang" -ErrorAction SilentlyContinue) -eq $null) {exit 1}})
        
      - name: Build binary
        run: |
          stack build --local-bin-path=bin --copy-bins
          ls bin
          
      - name: Rename binary to platform specific name
        working-directory: ./bin
        run: |
          Get-ChildItem binary-exe* | Rename-Item -NewName ("${{github.repository}}".Split("/")[-1] + "-win-amd64.exe")
          
      - name: Add binary name to ENV
        working-directory: ./bin
        run: |
          echo "BINARY_NAME=$((Get-ChildItem * | Select-Object -First 1).Name)" >> $env:GITHUB_ENV
          echo "${{env.BINARY_NAME}}"
        
      - name: Add Windows binary to release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
          
          
      - name: Job summary
        shell: bash
        run: |
          echo "### ✔ Build ${{runner.os}}" >> $GITHUB_STEP_SUMMARY
      
      - name: Run performance test
        id: perf-test
        uses: ./.github/actions/test_performance
        with:
          binary-name: ${{env.BINARY_NAME}}
          binary-run-command: ${{env.BINARY_NAME}}
          
      
      - name: Perf test summary
        shell: bash
        run: |
          cat ${{steps.perf-test.outputs.md-output}} >> $GITHUB_STEP_SUMMARY
          echo "MD_REPORT<<EOF" >> $GITHUB_ENV
          echo "<details><summary>📈 Performance test. <b>[${{runner.os}}]</b> build</summary>" >> $GITHUB_ENV
          echo -e "\n<br>\n" >> $GITHUB_ENV
          cat ${{steps.perf-test.outputs.md-output}} >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "</details>" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Add report to release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{env.MD_REPORT}}
          append_body: true
